version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    container_name: nodejs
    ports:
      - 80:3000
  db:
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: express-sample
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306